modules:
  warps: true
  afk: true
#COMMANDS
#
# Just comment out command rather than removing it
commands:
  - god
  - nickname
  - heal
  - spawn
  - gamemode
  - give
  - enchant
  - economy
  - balance
  - reload
  - mute
  - tpaccept
  - tprequest
  - fly
  - afk
  - warp
  - warps
  - magnet
  - tpdeny
#MAGNET
magnet-pickup:
  sound: ENTITY_ITEM_PICKUP
  volume: 1
  pitch: 1
magnet-always-enabled: false
magnet-block-drops: true
magnet-mob-drops: true
magnet-exp: true
#CHAT
join-message: "&a&l+ &r{player}"
leave-message: "&c&l- &r{player}"
format: "%player% > %message%"
hover-enabled: false
hover:
  - "line1"
  - "line2"
  - "line3"